/**
 * A sample board for trying Marie Kondo: an engineering team's sprint
 * retrospective, as it looks before anyone sorts it. Seven themes; a few
 * notes say what another says in other words (for Find similar), and one
 * was written word for word by two people.
 */
export const DEMO_NOTES: string[] = [
    // builds and deploys
    "CI takes 40 minutes to go green",
    "Every CI build makes us wait 40 minutes",
    "Docker images rebuild from scratch on every push",
    "Cache npm dependencies in CI",
    "The build queue backs up every afternoon",
    "Deploys to production still need a manual approval",
    "Rollback script failed during Friday's deploy",
    "Staging environment was down twice this sprint",
    "Preview environments for every branch would save hours",
    "Ship smaller deploys behind feature flags",
    "Run CI jobs in parallel to cut the wait",
    "Nightly build broke three times this week",
    // tests and code review
    "Flaky end-to-end tests blocked merges three times",
    "Flaky end-to-end tests blocked merges three times",
    "End-to-end tests fail at random",
    "Code reviews take two days to start",
    "Huge changes are impossible to review properly",
    "Snapshot tests break on every small UI change",
    "Add contract tests between the web app and the API",
    "Nobody owns the list of flaky tests",
    "Code review comments feel nitpicky",
    "Test coverage dropped below 60%",
    "Pair reviews on risky migrations caught real bugs",
    "Write a failing test before fixing a bug",
    // meetings
    "Too many meetings on Tuesdays",
    "So many meetings there is no time left to code",
    "Standup runs over 30 minutes every day",
    "Sprint planning took the whole morning",
    "Try async standups in Slack",
    "Nobody reads the meeting notes",
    "Block a no-meeting Wednesday",
    "Half the meetings could have been an email",
    "Retro action items never get done",
    "Cancel the weekly status meeting",
    "Keep meetings to 25 minutes",
    "Estimation meetings drag on for hours",
    // on-call and incidents
    "Paged at 3am for a disk alert that cleared itself",
    "Too many alerts, so real incidents get missed",
    "So many noisy alerts we miss the real ones",
    "Payments outage took two hours to detect",
    "Runbooks are missing for half our services",
    "On-call handover has no checklist",
    "Postmortems turn into blame sessions",
    "Status page was updated an hour after the outage",
    "Add SLO alerts for checkout latency",
    "We have never run a database failover drill",
    "Escalation path during the outage was unclear",
    "Too many pages on the weekend rotation",
    // docs and onboarding
    "README setup steps are out of date",
    "Onboarding took a week before a new hire could run the app",
    "No docs for the billing service",
    "Architecture diagram is from 2023",
    "Pair new joiners with a buddy for their first month",
    "Write decision records for big technical choices",
    "Knowledge lives in one person's head",
    "An onboarding checklist would help new hires",
    "Docs are spread across three different wikis",
    "Record a video tour of the codebase",
    "API docs don't match the real endpoints",
    "API documentation is out of date",
    // wins and kudos
    "Shipped the new search on time 🎉",
    "Kudos to Mai for the great demo",
    "Great collaboration with the design team",
    "Working with the design team was a joy",
    "Customer satisfaction went up 12 points",
    "Launch day went smoothly 🚀",
    "Demo day was fun, let's keep doing it",
    "Kudos to Leo for the migration plan",
    "Pairing sessions were really productive",
    "Love the new design system components",
    "Crash rate in the mobile app is down by half",
    "Kudos to support for handling the launch rush",
    // workload and focus
    "Too much context switching between projects",
    "Scope kept growing in the middle of the sprint",
    "Need more uninterrupted focus time",
    "Worked overtime again to hit the deadline",
    "Tired of working overtime every week",
    "Priorities change every week",
    "Too many urgent requests from sales",
    "Half the sprint went to unplanned work",
    "Protect focus time in the afternoons",
    "We're burning out, the next sprint should be lighter",
    "Interrupted by support questions all day",
    "Nobody knows which project comes first",
];
