/**
 * Generates src/shared/icons.ts: the few Lucide icons Sensemaker uses, as
 * inline SVG strings. Drawdy's marketplace build allows no npm imports, so the
 * icons are copied in rather than imported from `lucide-static`.
 *
 * Usage: node scripts/icons.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const LUCIDE = join(ROOT, "node_modules/lucide-static");

/** Name in our code → Lucide icon name. */
const ICONS = {
    group: "group",
    similar: "scan-search",
    sample: "sticky-note",
    search: "search",
    note: "sticky-note",
    text: "type",
    shape: "square",
    image: "image",
    sparkles: "sparkles",
    download: "download",
    chevronLeft: "chevron-left",
    chevronRight: "chevron-right",
} as const;

const svgOf = (name: string): string =>
    readFileSync(join(LUCIDE, "icons", `${name}.svg`), "utf8")
        .replace(/<!--[\s\S]*?-->/g, "")
        .replace(/\s*class="[^"]*"/, ' class="icon" aria-hidden="true"')
        .replace(/\s*(width|height)="24"/g, "")
        .replace(/\s+/g, " ")
        .replace(/> </g, "><")
        .trim();

const { version } = JSON.parse(readFileSync(join(LUCIDE, "package.json"), "utf8")) as { version: string };
const entries = Object.entries(ICONS).map(([key, name]) => `    ${key}: ${JSON.stringify(svgOf(name))},`);

writeFileSync(
    join(ROOT, "src/shared/icons.ts"),
    `/**
 * Lucide icons (https://lucide.dev), lucide-static ${version}, ISC License,
 * Copyright (c) Lucide Icons and Contributors.
 *
 * Generated by scripts/icons.ts. Do not edit.
 */

export const ICONS = {
${entries.join("\n")}
} as const;

export type IconName = keyof typeof ICONS;
`
);
console.log(`wrote ${Object.keys(ICONS).length} icons from lucide-static ${version}`);
